services:
  web:
    image: php:8.2-apache
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mariadb
    command: >
      bash -c "docker-php-ext-install pdo pdo_mysql && apache2-foreground"

  mariadb:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: PHP
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./Usuarios.sql:/docker-entrypoint-initdb.d/Usuarios.sql

  phpmyadmin:
    image:  phpmyadmin/phpmyadmin
    ports:
      - "8000:80"
    environment:
      PMA_HOST: mariadb

volumes:
  mariadb_data: